-- Lager Gotland v31.2
-- Kör hela koden EN GÅNG i Supabase SQL Editor.

create table if not exists public.miniminiva (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  artikelnummer text not null,
  plats text not null,
  min_antal integer not null default 0 check (min_antal >= 0),
  unique (artikelnummer, plats)
);

alter table public.miniminiva enable row level security;

drop policy if exists "lager_read_miniminiva" on public.miniminiva;
drop policy if exists "lager_insert_miniminiva" on public.miniminiva;
drop policy if exists "lager_update_miniminiva" on public.miniminiva;
drop policy if exists "lager_delete_miniminiva" on public.miniminiva;

create policy "lager_read_miniminiva"
on public.miniminiva for select
to anon, authenticated
using (true);

create policy "lager_insert_miniminiva"
on public.miniminiva for insert
to anon, authenticated
with check (true);

create policy "lager_update_miniminiva"
on public.miniminiva for update
to anon, authenticated
using (true)
with check (true);

create policy "lager_delete_miniminiva"
on public.miniminiva for delete
to anon, authenticated
using (true);

grant select, insert, update, delete on table public.miniminiva to anon, authenticated;
grant usage, select on sequence public.miniminiva_id_seq to anon, authenticated;
