-- Lager Gotland v32 – ToDo
create table if not exists public.todo_jobs (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 customer text not null default '',
 job_type text not null default '',
 description text not null default '',
 priority text not null default 'Normal',
 status text not null default 'Aktiv',
 needs_part boolean not null default false,
 article_no text not null default '',
 part_name text not null default '',
 part_qty integer not null default 1 check (part_qty >= 1)
);
alter table public.todo_jobs enable row level security;
drop policy if exists "todo_read" on public.todo_jobs;
drop policy if exists "todo_insert" on public.todo_jobs;
drop policy if exists "todo_update" on public.todo_jobs;
drop policy if exists "todo_delete" on public.todo_jobs;
create policy "todo_read" on public.todo_jobs for select to anon, authenticated using (true);
create policy "todo_insert" on public.todo_jobs for insert to anon, authenticated with check (true);
create policy "todo_update" on public.todo_jobs for update to anon, authenticated using (true) with check (true);
create policy "todo_delete" on public.todo_jobs for delete to anon, authenticated using (true);
grant select,insert,update,delete on public.todo_jobs to anon,authenticated;
grant usage,select on sequence public.todo_jobs_id_seq to anon,authenticated;
